-   id: check-line-length
    name: check line length
    description: verify line length doesn't cross threshold
    entry: line-length-checker
    language: python
    files: .*\.f90$

-   id: detect-deprecated-symbols
    name: detect deprecated symbols
    description: detect symbols that are deprecated after fortran77
    entry: detect-deprecated-symbols
    language: python
    files: .*\.f90$